config/routes.rb
Certificates::Application.routes.draw do
  
  get "home/index"

  scope '(:locale)' do
    resources :forms
    resources :categories
    
    root :to => 'home#index', as: 'home'
  end

  root :to => 'home#index', as: 'home'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forms }
    end
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    @form = Form.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @form }
    end
  end

  # GET /forms/new
  # GET /forms/new.json
  def new
    @form = Form.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @form }
    end
  end

  # GET /forms/1/edit
  def edit
    @form = Form.find(params[:id])
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(params[:form])

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render json: @form, status: :created, location: @form }
      else
        format.html { render action: "new" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forms/1
  # PUT /forms/1.json
  def update
    @form = Form.find(params[:id])

    respond_to do |format|
      if @form.update_attributes(params[:form])
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form = Form.find(params[:id])
    @form.destroy

    respond_to do |format|
      format.html { redirect_to forms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_of_sertificate %><br />
    <%= f.text_field :type_of_sertificate %>
  </div>
  <div class="field">
    <%= f.label :type_of_legal_entity %><br />
    <%= f.text_field :type_of_legal_entity %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :registered_address %><br />
    <%= f.text_field :registered_address %>
  </div>
  <div class="field">
    <%= f.label :actual_address %><br />
    <%= f.text_field :actual_address %>
  </div>
  <div class="field">
    <%= f.label :address_on_english %><br />
    <%= f.text_field :address_on_english %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :inn %><br />
    <%= f.text_field :inn %>
  </div>
  <div class="field">
    <%= f.label :kpp %><br />
    <%= f.text_field :kpp %>
  </div>
  <div class="field">
    <%= f.label :ogrn %><br />
    <%= f.text_field :ogrn %>
  </div>
  <div class="field">
    <%= f.label :bank %><br />
    <%= f.text_field :bank %>
  </div>
  <div class="field">
    <%= f.label :current_account %><br />
    <%= f.text_field :current_account %>
  </div>
  <div class="field">
    <%= f.label :correspondent_account %><br />
    <%= f.text_field :correspondent_account %>
  </div>
  <div class="field">
    <%= f.label :bik %><br />
    <%= f.text_field :bik %>
  </div>
  <div class="field">
    <%= f.label :bank_person %><br />
    <%= f.text_field :bank_person %>
  </div>
  <div class="field">
    <%= f.label :auditors_names %><br />
    <%= f.text_field :auditors_names %>
  </div>
  <div class="field">
    <%= f.label :categories_list_of_works %><br />
    <%= f.text_field :categories_list_of_works %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<h1>Listing forms</h1>

<table>
  <tr>
    <th>Type of sertificate</th>
    <th>Type of legal entity</th>
    <th>Company</th>
    <th>Creator</th>
    <th>Registered address</th>
    <th>Actual address</th>
    <th>Address on english</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>Email</th>
    <th>Inn</th>
    <th>Kpp</th>
    <th>Ogrn</th>
    <th>Bank</th>
    <th>Current account</th>
    <th>Correspondent account</th>
    <th>Bik</th>
    <th>Bank person</th>
    <th>Auditors names</th>
    <th>Categories list of works</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forms.each do |form| %>
  <tr>
    <td><%= form.type_of_sertificate %></td>
    <td><%= form.type_of_legal_entity %></td>
    <td><%= form.company %></td>
    <td><%= form.creator %></td>
    <td><%= form.registered_address %></td>
    <td><%= form.actual_address %></td>
    <td><%= form.address_on_english %></td>
    <td><%= form.phone %></td>
    <td><%= form.fax %></td>
    <td><%= form.email %></td>
    <td><%= form.inn %></td>
    <td><%= form.kpp %></td>
    <td><%= form.ogrn %></td>
    <td><%= form.bank %></td>
    <td><%= form.current_account %></td>
    <td><%= form.correspondent_account %></td>
    <td><%= form.bik %></td>
    <td><%= form.bank_person %></td>
    <td><%= form.auditors_names %></td>
    <td><%= form.categories_list_of_works %></td>
    <td><%= link_to 'Show', form %></td>
    <td><%= link_to 'Edit', edit_form_path(form) %></td>
    <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type of sertificate:</b>
  <%= @form.type_of_sertificate %>
</p>

<p>
  <b>Type of legal entity:</b>
  <%= @form.type_of_legal_entity %>
</p>

<p>
  <b>Company:</b>
  <%= @form.company %>
</p>

<p>
  <b>Creator:</b>
  <%= @form.creator %>
</p>

<p>
  <b>Registered address:</b>
  <%= @form.registered_address %>
</p>

<p>
  <b>Actual address:</b>
  <%= @form.actual_address %>
</p>

<p>
  <b>Address on english:</b>
  <%= @form.address_on_english %>
</p>

<p>
  <b>Phone:</b>
  <%= @form.phone %>
</p>

<p>
  <b>Fax:</b>
  <%= @form.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @form.email %>
</p>

<p>
  <b>Inn:</b>
  <%= @form.inn %>
</p>

<p>
  <b>Kpp:</b>
  <%= @form.kpp %>
</p>

<p>
  <b>Ogrn:</b>
  <%= @form.ogrn %>
</p>

<p>
  <b>Bank:</b>
  <%= @form.bank %>
</p>

<p>
  <b>Current account:</b>
  <%= @form.current_account %>
</p>

<p>
  <b>Correspondent account:</b>
  <%= @form.correspondent_account %>
</p>

<p>
  <b>Bik:</b>
  <%= @form.bik %>
</p>

<p>
  <b>Bank person:</b>
  <%= @form.bank_person %>
</p>

<p>
  <b>Auditors names:</b>
  <%= @form.auditors_names %>
</p>

<p>
  <b>Categories list of works:</b>
  <%= @form.categories_list_of_works %>
</p>


<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>